/* Auto-generated by genmsg_cpp for file /home/atmgast/workspace/Release1.1/ros/deltaRobotNode/msg/Calibration.msg */
#ifndef DELTAROBOTNODE_MESSAGE_CALIBRATION_H
#define DELTAROBOTNODE_MESSAGE_CALIBRATION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace deltaRobotNode
{
template <class ContainerAllocator>
struct Calibration_ {
  typedef Calibration_<ContainerAllocator> Type;

  Calibration_()
  {
  }

  Calibration_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::deltaRobotNode::Calibration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deltaRobotNode::Calibration_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Calibration
typedef  ::deltaRobotNode::Calibration_<std::allocator<void> > Calibration;

typedef boost::shared_ptr< ::deltaRobotNode::Calibration> CalibrationPtr;
typedef boost::shared_ptr< ::deltaRobotNode::Calibration const> CalibrationConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::deltaRobotNode::Calibration_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::deltaRobotNode::Calibration_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace deltaRobotNode

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::deltaRobotNode::Calibration_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::deltaRobotNode::Calibration_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::deltaRobotNode::Calibration_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::deltaRobotNode::Calibration_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::deltaRobotNode::Calibration_<ContainerAllocator> > {
  static const char* value() 
  {
    return "deltaRobotNode/Calibration";
  }

  static const char* value(const  ::deltaRobotNode::Calibration_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::deltaRobotNode::Calibration_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::deltaRobotNode::Calibration_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::deltaRobotNode::Calibration_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::deltaRobotNode::Calibration_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Calibration_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deltaRobotNode::Calibration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::deltaRobotNode::Calibration_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // DELTAROBOTNODE_MESSAGE_CALIBRATION_H

