/* Auto-generated by genmsg_cpp for file /home/atmgast/workspace/Release1.1/ros/deltaRobotNode/msg/Motion.msg */
#ifndef DELTAROBOTNODE_MESSAGE_MOTION_H
#define DELTAROBOTNODE_MESSAGE_MOTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace deltaRobotNode
{
template <class ContainerAllocator>
struct Motion_ {
  typedef Motion_<ContainerAllocator> Type;

  Motion_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , speed(0.0)
  {
  }

  Motion_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , speed(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;

  typedef double _speed_type;
  double speed;


  typedef boost::shared_ptr< ::deltaRobotNode::Motion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deltaRobotNode::Motion_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Motion
typedef  ::deltaRobotNode::Motion_<std::allocator<void> > Motion;

typedef boost::shared_ptr< ::deltaRobotNode::Motion> MotionPtr;
typedef boost::shared_ptr< ::deltaRobotNode::Motion const> MotionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::deltaRobotNode::Motion_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::deltaRobotNode::Motion_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace deltaRobotNode

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::deltaRobotNode::Motion_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::deltaRobotNode::Motion_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::deltaRobotNode::Motion_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dbc4987e9444b6c324bfd4af3f59c40f";
  }

  static const char* value(const  ::deltaRobotNode::Motion_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdbc4987e9444b6c3ULL;
  static const uint64_t static_value2 = 0x24bfd4af3f59c40fULL;
};

template<class ContainerAllocator>
struct DataType< ::deltaRobotNode::Motion_<ContainerAllocator> > {
  static const char* value() 
  {
    return "deltaRobotNode/Motion";
  }

  static const char* value(const  ::deltaRobotNode::Motion_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::deltaRobotNode::Motion_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 speed\n\
";
  }

  static const char* value(const  ::deltaRobotNode::Motion_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::deltaRobotNode::Motion_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::deltaRobotNode::Motion_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.speed);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Motion_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deltaRobotNode::Motion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::deltaRobotNode::Motion_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DELTAROBOTNODE_MESSAGE_MOTION_H

